version: "3.9"
services:
  mysql:
    ports:
      - "3306:3306"

  backend:
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5000:5000"

  frontend:
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"

  nginx:
    ports:
      - "8080:80"

